### ISSUE TITLE
Archive this repo or remove it from probot org

### ISSUE THREAD

**Issue by hiimbex** [probot/owners#16]
This app's main purpose has been basically replaced by code owners.

Checking [this search](https://github.com/search?q=org%3Aprobot+commenter%3Aapp%2Fowners&type=Issues), it appears we are the only ones using the bot. Also the bot has had a lot of recent failed deliveries as well.

Might be time to say goodbye 😢 👋 

cc/ @bkeepers

**Comment by bkeepers** [comment]
👍 I transferred to my personal account
